// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/15/2025, 10:47:25 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/soureino/Documents/PROJETOS DEV /UBIZ AUTOMATICFLOW/netcom-crm/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/soureino/Documents/PROJETOS DEV /UBIZ AUTOMATICFLOW/netcom-crm/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/soureino/Documents/PROJETOS DEV /UBIZ AUTOMATICFLOW/netcom-crm/components/ui/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/soureino/Documents/PROJETOS DEV /UBIZ AUTOMATICFLOW/netcom-crm/components/forms/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/soureino/Documents/PROJETOS DEV /UBIZ AUTOMATICFLOW/netcom-crm/components/feedback/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/soureino/Documents/PROJETOS DEV /UBIZ AUTOMATICFLOW/netcom-crm/components/layout/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/soureino/Documents/PROJETOS DEV /UBIZ AUTOMATICFLOW/netcom-crm/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/soureino/Documents/PROJETOS DEV /UBIZ AUTOMATICFLOW/netcom-crm/plugins/**/*.{js,ts,mjs}","/Users/soureino/Documents/PROJETOS DEV /UBIZ AUTOMATICFLOW/netcom-crm/composables/**/*.{js,ts,mjs}","/Users/soureino/Documents/PROJETOS DEV /UBIZ AUTOMATICFLOW/netcom-crm/utils/**/*.{js,ts,mjs}","/Users/soureino/Documents/PROJETOS DEV /UBIZ AUTOMATICFLOW/netcom-crm/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/soureino/Documents/PROJETOS DEV /UBIZ AUTOMATICFLOW/netcom-crm/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/soureino/Documents/PROJETOS DEV /UBIZ AUTOMATICFLOW/netcom-crm/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/soureino/Documents/PROJETOS DEV /UBIZ AUTOMATICFLOW/netcom-crm/app.config.{js,ts,mjs}","/Users/soureino/Documents/PROJETOS DEV /UBIZ AUTOMATICFLOW/netcom-crm/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;